/* Sitios ficticios de Firefox: contenido e ilustraciones locales. */
const firefoxCart = new Set();

function firefoxArt(kind) {
  const scene = kind === 'product'
    ? '<rect x="90" y="35" width="140" height="165" rx="10" fill="#fff"/><path d="M110 35v165" stroke="#c4b298" stroke-width="3"/><rect x="128" y="65" width="80" height="62" rx="6" fill="#eadfcd"/><path d="m147 95 13 12 24-27M132 150h66M132 165h43" fill="none" stroke="#876e49" stroke-width="5" stroke-linecap="round"/><ellipse cx="160" cy="216" rx="88" ry="8" fill="#bfae93" opacity=".3"/>'
    : '<circle cx="253" cy="61" r="35" fill="#bad1c2"/><rect x="53" y="53" width="172" height="116" rx="8" fill="#fff"/><rect x="65" y="65" width="148" height="90" rx="3" fill="#e2ece4"/><path d="M87 92h50M87 109h94M87 126h74" stroke="#688c75" stroke-width="7" stroke-linecap="round"/><path d="M125 171v17h33v-17M95 191h94" stroke="#44624e" stroke-width="7" stroke-linecap="round"/><path d="M256 188v-51m0 29c-29-2-29-30-29-30 27 0 29 30 29 30m0-13c26-2 28-29 28-29-25 0-28 29-28 29" fill="#789b80" stroke="#789b80" stroke-width="3"/>';
  return `<svg viewBox="0 0 320 240" role="img" aria-label="${kind === 'product' ? 'Cuaderno de aprendizaje ilustrado' : 'Ilustración de un espacio de estudio'}"><rect width="320" height="240" rx="12" fill="${kind === 'product' ? '#f1eadf' : '#eaf0e9'}"/>${scene}</svg>`;
}

function firefoxRelated(results, current) {
  return results.filter(r => r.index !== current).map(r => `<a href="#" onclick="event.preventDefault();firefoxOpen(${r.index})">${firefoxEscape(r.title)} <span aria-hidden="true">↗</span></a>`).join('');
}

function firefoxAddCart(button) {
  const state = firefoxHistory[firefoxHistory.length - 1];
  if (state.type !== 'article' || !pmProcesoAplicacion('firefox')) return;
  firefoxCart.add(state.query);
  button.textContent = 'Añadido al carrito';
  button.disabled = true;
  const count = document.getElementById('ff-cart-count');
  if (count) count.textContent = firefoxCart.size;
  const status = document.getElementById('ff-cart-status');
  if (status) status.textContent = 'Tu cuaderno está en el carrito de demostración.';
}

function firefoxPage(result, results, query) {
  const e = firefoxEscape;
  const title = e(result.title), q = e(query);
  const intro = e(result.topic.intro), example = e(result.topic.example), practice = e(result.topic.practice);
  const related = firefoxRelated(results, result.index);
  const index = '<a href="#ff-overview">Introducción</a><a href="#ff-examples">Ejemplos</a><a href="#ff-practice">Para profundizar</a>';
  switch (result.template) {
    case 'wiki':
      return `<div class="ff-site ff-wiki"><header class="ff-wiki-masthead"><span class="ff-wiki-mark">${firefoxSiteIcon(0)}</span><div><b>Aula Abierta</b><small>La enciclopedia del aprendizaje</small></div></header><div class="ff-wiki-grid"><aside class="ff-wiki-index"><b>Contenido</b>${index}<a href="#ff-related">Otros recursos</a></aside><article><h1>${title}</h1><div class="ff-wiki-tabs"><b>Artículo</b><span>Lectura</span></div><aside class="ff-wiki-facts"><b>${q}</b>${firefoxArt('study')}<dl><dt>Área</dt><dd>Conocimiento general</dd><dt>Contenido</dt><dd>Conceptos y ejemplos</dd><dt>Nivel</dt><dd>Introductorio</dd></dl></aside><section id="ff-overview"><p>${intro}</p><p>Este artículo presenta una introducción al tema y un punto de partida para organizar su estudio.</p></section><section id="ff-examples"><h2>Ejemplos y aplicaciones</h2><p>${example}</p></section><section id="ff-practice"><h2>Para profundizar</h2><p>${practice}</p><ul><li>Identifica las ideas principales.</li><li>Relaciona cada concepto con un ejemplo.</li><li>Compara lo aprendido con otros recursos.</li></ul></section><section id="ff-related" class="ff-related"><h2>Véase también</h2>${related}</section></article></div></div>`;
    case 'blog':
      return `<div class="ff-site ff-blog"><header class="ff-blog-masthead"><b>Perspectiva<span>.</span></b><span>Ideas que vale la pena explorar</span></header><article class="ff-blog-story"><p class="ff-eyebrow">APRENDER · IDEAS</p><h1>${title}</h1><p class="ff-blog-deck">Una mirada sencilla para comprender el tema y llevarlo a la práctica.</p><div class="ff-byline"><svg viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="20" fill="#dfe9dc"/><circle cx="20" cy="15" r="7" fill="#68806a"/><path d="M7 36c0-15 26-15 26 0" fill="#68806a"/></svg><span><b>Equipo Perspectiva</b><small>22 septiembre 2026 · 4 min de lectura</small></span></div><figure>${firefoxArt('study')}<figcaption>Un espacio para detenerse, comprender y aprender.</figcaption></figure><p class="ff-blog-first">${intro}</p><h2>Del concepto a lo cotidiano</h2><p>${example}</p><blockquote>Aprender también es encontrar buenas preguntas.</blockquote><h2>Tu próximo paso</h2><p>${practice}</p><details><summary>Una idea para tu cuaderno</summary><p>Escribe un resumen breve y añade un ejemplo propio. Después, explica el tema a alguien con palabras sencillas.</p></details><section class="ff-related"><h2>Sigue leyendo</h2>${related}</section></article></div>`;
    case 'shop': {
      const added = firefoxCart.has(query);
      return `<div class="ff-site ff-shop"><header class="ff-shop-masthead"><b>Estudio / Objetos</b><span>Carrito <b id="ff-cart-count">${firefoxCart.size}</b></span></header><p class="ff-shop-breadcrumb">Colección de aprendizaje / Cuadernos temáticos</p><div class="ff-product"><div class="ff-product-picture">${firefoxArt('product')}<span>EDICIÓN DE ESTUDIO</span></div><section><p class="ff-eyebrow">COLECCIÓN ESENCIAL</p><h1>${title}</h1><p class="ff-product-subtitle">Un lugar para ordenar tus ideas sobre ${q}.</p><p class="ff-price">$12.00 <small>Precio de ejemplo</small></p><p>Cuaderno ilustrado con espacios para conceptos, ejemplos y ejercicios. Una propuesta de producto para acompañar tu aprendizaje.</p><ul class="ff-product-features"><li>Formato A5 · 80 páginas</li><li>Guías de repaso y espacio para notas</li><li>Portada mate · color arena</li></ul><button class="ff-cart-button" onclick="firefoxAddCart(this)" ${added ? 'disabled' : ''}>${added ? 'Añadido al carrito' : 'Añadir al carrito'}</button><p id="ff-cart-status" class="ff-muted" role="status">${added ? 'Tu cuaderno está en el carrito de demostración.' : 'Producto de muestra · sin compras reales'}</p></section></div><section class="ff-shop-details"><h2>Dentro del cuaderno</h2><div class="ff-product-cards"><article><b>01 / Comprende</b><p>${intro}</p></article><article><b>02 / Explora</b><p>${example}</p></article><article><b>03 / Practica</b><p>${practice}</p></article></div><details><summary>Detalles de esta edición</summary><p>Incluye hojas de notas, listas de conceptos y actividades. El carrito funciona únicamente como demostración local.</p></details><section class="ff-related"><h2>Antes de empezar</h2>${related}</section></section></div>`;
    }
    case 'docs':
      return `<div class="ff-site ff-docs"><header class="ff-docs-masthead"><b><span aria-hidden="true">{ }</span> Guía práctica</b><span>Documentación / Inicio</span></header><div class="ff-docs-grid"><aside class="ff-docs-menu"><small>GUÍA DE APRENDIZAJE</small><a href="#ff-overview" class="ff-docs-selected">Primeros pasos</a><a href="#ff-examples">Ejemplo práctico</a><a href="#ff-practice">Comprueba lo aprendido</a><a href="#ff-related">Más recursos</a></aside><article><p class="ff-eyebrow">GUÍAS / INTRODUCCIÓN</p><h1>${title}</h1><p class="ff-docs-lead">Un recorrido ordenado desde los conceptos hasta la práctica.</p><section id="ff-overview"><h2>1. Comprende el concepto</h2><p>${intro}</p><aside class="ff-docs-note"><b>Antes de empezar</b><p>No necesitas conocimientos avanzados. Toma notas de las palabras que quieras investigar.</p></aside></section><section id="ff-examples"><h2>2. Revisa un ejemplo</h2><p>${example}</p><div class="ff-docs-example"><span>SECUENCIA DE ESTUDIO</span><pre><code>01  Leer el concepto\n02  Identificar sus elementos\n03  Relacionarlos con un ejemplo\n04  Explicar el resultado</code></pre></div></section><section id="ff-practice"><h2>3. Comprueba lo aprendido</h2><p>${practice}</p><label class="ff-docs-check"><input type="checkbox"> Puedo explicarlo con mis propias palabras</label><details><summary>Ver una orientación</summary><p>Una buena explicación incluye qué significa el concepto, para qué sirve y un ejemplo concreto.</p></details></section><section id="ff-related" class="ff-related"><h2>Continúa con</h2>${related}</section></article></div></div>`;
    case 'forum':
      return `<div class="ff-site ff-forum"><header class="ff-forum-masthead"><b>${firefoxSiteIcon(4)} Punto de encuentro</b><span>Comunidad de aprendizaje</span></header><div class="ff-forum-grid"><main><p class="ff-eyebrow">PREGUNTAS / APRENDER</p><h1>${title}</h1><p class="ff-forum-meta">Conversación de ejemplo · 2 respuestas</p><article class="ff-question"><div class="ff-forum-user"><span class="ff-avatar">${firefoxSiteIcon(0)}</span><b>Estudiante curioso</b><small>Pregunta</small></div><p>Estoy empezando a estudiar ${q}. ¿Cómo puedo entender las ideas principales y encontrar un ejemplo sencillo?</p><span class="ff-tag">aprendizaje</span><span class="ff-tag">conceptos</span></article><h2 class="ff-answers-title">2 respuestas</h2><article class="ff-answer ff-accepted"><p class="ff-accepted-label">✓ Respuesta aceptada</p><div class="ff-forum-user"><span class="ff-avatar">${firefoxSiteIcon(1)}</span><b>Comunidad Aula</b></div><p>${intro}</p><p>${example}</p></article><article class="ff-answer"><div class="ff-forum-user"><span class="ff-avatar">${firefoxSiteIcon(3)}</span><b>Guía de estudio</b></div><p>${practice}</p><p>También ayuda comparar tus notas con otra explicación del mismo tema.</p></article></main><aside><section class="ff-forum-about"><b>Un espacio para aprender</b><p>Preguntas claras, ejemplos sencillos y respuestas que ayudan a comprender.</p><div><span>5<br><small>recursos del tema</small></span><span>2<br><small>respuestas</small></span></div></section><section class="ff-related"><h2>Recursos relacionados</h2>${related}</section></aside></div></div>`;
    default: return '';
  }
}
